{% set name = "phroc" %}
{% set version = "0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/phroc-{{ version }}.tar.gz
  sha256: 1fd9d27438ad3095fd65d103ac71f73a53f7e763498efe88c2d030d04f35e144

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9
    - setuptools
    - pip
  run:
    - python >=3.9
    - koolstof
    - numpy
    - pandas
    - pyside6
    - matplotlib-base
    - pyarrow
    - openpyxl

test:
  imports:
    - phroc
  commands:
    - pip check
  requires:
    - pip

about:
  summary: GUI for processing spectrophotometric pH data
  license: GPL-3.0-only
  license_file: LICENSE
  home: https://github.com/mvdh7/phroc

extra:
  recipe-maintainers:
    - mvdh7
