{% set name = "phroc" %}
{% set version = "0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/phroc-{{ version }}.tar.gz
  sha256: e1fdccc4a22b8e5e924121b9f871d4d7deb67f18286bdceec46e6617f29a6967

build:
  entry_points:
    - phroc = phroc:phroc_run
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9
    - setuptools
    - pip
  run:
    - python >=3.9
    - koolstof
    - numpy
    - pandas
    - pyside6
    - matplotlib-base
    - pyarrow
    - openpyxl

test:
  imports:
    - phroc
  commands:
    - pip check
  requires:
    - pip

about:
  summary: GUI for processing spectrophotometric pH data
  license: GPL-3.0-only
  license_file: LICENSE
  home: https://github.com/mvdh7/phroc

extra:
  recipe-maintainers:
    - mvdh7
